(function(){
angular.module("DonutApp").directive("employeeDirective",[function(){
    return{
        restrict:"EA",
        templateUrl:"employeeDetails.html",
        controller:"loginCtrl"
    };
}]);
})();
